version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp

  rustapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - backend
